version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "ecomm"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "@Ashish7797"
      MYSQL_ROOT_PASSWORD: "@Ashish7797"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: .
    command: python /ecomm/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ecomm
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
