# Generated by Django 5.0.2 on 2024-03-09 10:47

import django.db.models.deletion
import orderItems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_auto_20240226_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('order', orderItems.models.IntegerForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodels')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
