import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ProductContextProvider } from "@/context/productContext/productContext";
import { CartContextProvider } from "@/context/cartContext/cartContext";
import { UserContextProvider } from "@/context/userContext/userContext";
import { LoaderContextProvider } from "@/context/loaderContext/loaderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LoaderContextProvider>
        <UserContextProvider>
          <ProductContextProvider>
            <CartContextProvider>
              <body className={inter.className}>
                <div className="fixed top-0 left-0 w-[100vw] z-10">
                  <Navbar />
                </div>
                <div className="mt-[70px]">{children}</div>
              </body>
            </CartContextProvider>
          </ProductContextProvider>
        </UserContextProvider>
      </LoaderContextProvider>
    </html>
  );
}
